[project]
name = "llm-ollama"
version = "0.5.0"
description = "LLM plugin providing access to local Ollama models"
readme = "README.md"
authors = [{ name = "Sergey Alexandrov" }]
license = { text = "Apache-2.0" }
classifiers = ["License :: OSI Approved :: Apache Software License"]
dependencies = ["llm", "ollama", "pydantic>=2"]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/taketwo/llm-ollama"
Changelog = "https://github.com/taketwo/llm-ollama/releases"
Issues = "https://github.com/taketwo/llm-ollama/issues"
CI = "https://github.com/taketwo/llm-ollama/actions"

[project.entry-points.llm]
ollama = "llm_ollama"

[project.optional-dependencies]
test = ["pytest"]
